# Generated by Django 5.2.7 on 2025-10-16 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.AutoField(primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=9, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=9, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='BusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=9, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=9, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='app.bus')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.route'),
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stop')),
            ],
            options={
                'ordering': ['stop_order'],
                'unique_together': {('route', 'stop_order')},
            },
        ),
    ]
